// LifePrint — seed recipe library (26 recipes) + ingredient-by-ingredient compliance validation.
// Nutrition values are ESTIMATES per serving, calculated from the seed food data.
import { getFood } from './foods.js';

/**
 * servings = base servings the quantities are written for (scaled at plan time).
 * ingredients: { foodId, qty, unit, note? } — every foodId must exist in foods.js.
 */
export const RECIPES = [
  {
    id: 'lemon-herb-sheet-pan-chicken',
    name: 'Lemon-herb sheet pan chicken and vegetables',
    cuisine: ['mediterranean'],
    mealTypes: ['dinner', 'lunch'],
    servings: 2,
    prepMin: 10,
    cookMin: 30,
    equipment: ['oven'],
    skill: 'beginner',
    budgetTier: 'moderate',
    ingredients: [
      { foodId: 'chicken-thigh', qty: 8, unit: 'oz' },
      { foodId: 'zucchini', qty: 2, unit: 'cups', note: 'thick half-moons' },
      { foodId: 'carrot', qty: 1, unit: 'cup', note: 'batons' },
      { foodId: 'olive-oil', qty: 2, unit: 'tbsp' },
      { foodId: 'lemon', qty: 1, unit: 'fruit' },
      { foodId: 'rosemary', qty: 1, unit: 'tsp' },
      { foodId: 'sea-salt', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      'Heat the oven to 425F and line a sheet pan.',
      'Toss the vegetables with half the oil and salt; push to the edges of the pan.',
      'Rub the chicken with the remaining oil, rosemary, and lemon zest; set it in the center.',
      'Roast 28-32 minutes until the chicken reaches 175F and the vegetable edges brown.',
      'Finish with a squeeze of lemon juice and rest 5 minutes before serving.',
    ],
    storage: 'Refrigerate up to 4 days. Reheat uncovered at 350F to keep the skin from going soft.',
    substitutions: [
      'Swap chicken thigh for chicken breast (reduce roast time to 22 minutes).',
      'Swap zucchini for green beans or acorn squash in cooler months.',
    ],
    batchNotes: 'Doubles cleanly across two sheet pans; rotate pans halfway.',
    tags: ['sheet-pan', 'high-protein', 'one-pan'],
  },
  {
    id: 'salmon-with-roasted-squash',
    name: 'Slow-roasted salmon with acorn squash',
    cuisine: ['mediterranean', 'american'],
    mealTypes: ['dinner'],
    servings: 2,
    prepMin: 10,
    cookMin: 35,
    equipment: ['oven'],
    skill: 'beginner',
    budgetTier: 'flexible',
    ingredients: [
      { foodId: 'salmon-wild', qty: 10, unit: 'oz' },
      { foodId: 'acorn-squash', qty: 2, unit: 'cups', note: 'cubed' },
      { foodId: 'olive-oil', qty: 2, unit: 'tbsp' },
      { foodId: 'thyme', qty: 1, unit: 'tsp' },
      { foodId: 'lemon', qty: 1, unit: 'fruit' },
      { foodId: 'arugula', qty: 2, unit: 'cups' },
    ],
    instructions: [
      'Roast the squash at 425F with 1 tbsp oil for 20 minutes.',
      'Lower the oven to 300F, move the squash to one side, and add the salmon skin-side down.',
      'Roast 14-18 minutes until the salmon flakes at the thickest point.',
      'Dress the arugula with the remaining oil and lemon juice and serve alongside.',
    ],
    storage: 'Best same day; refrigerate up to 2 days and eat cold over greens rather than reheating.',
    substitutions: ['Trout or cod work in place of salmon.', 'Butternut squash for acorn squash.'],
    batchNotes: 'Roast an extra fillet for next-day salads.',
    tags: ['omega3', 'high-protein'],
  },
  {
    id: 'coconut-braised-greens-plantain',
    name: 'Coconut-braised greens with caramelized plantain',
    cuisine: ['caribbean'],
    mealTypes: ['dinner', 'lunch'],
    servings: 2,
    prepMin: 10,
    cookMin: 25,
    equipment: ['stovetop'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'collard-greens', qty: 4, unit: 'cups', note: 'ribbons' },
      { foodId: 'coconut-milk-canned', qty: 1, unit: 'cup' },
      { foodId: 'plantain', qty: 2, unit: 'cups', note: 'sliced on the bias' },
      { foodId: 'ginger', qty: 2, unit: 'tsp', note: 'grated' },
      { foodId: 'coconut-oil', qty: 1, unit: 'tbsp' },
      { foodId: 'lime', qty: 1, unit: 'fruit' },
      { foodId: 'sea-salt', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      'Melt the coconut oil and caramelize the plantain slices 3-4 minutes per side; set aside.',
      'Add ginger to the pan for 30 seconds, then the greens and coconut milk.',
      'Simmer 15-18 minutes until the greens are silky and the sauce thickens.',
      'Season with salt and lime and spoon the plantain back over the top.',
    ],
    storage: 'Refrigerate up to 4 days; the greens improve overnight.',
    substitutions: ['Kale or Swiss chard for collards.', 'Cassava for plantain.'],
    batchNotes: 'Braise a double batch of greens and cook plantain fresh each time.',
    tags: ['aip-friendly', 'vegan', 'low-fodmap'],
  },
  {
    id: 'roasted-root-bowl',
    name: 'Roasted root vegetable bowl with herb oil',
    cuisine: ['american'],
    mealTypes: ['lunch', 'dinner'],
    servings: 2,
    prepMin: 15,
    cookMin: 35,
    equipment: ['oven'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'carrot', qty: 2, unit: 'cups' },
      { foodId: 'parsnip', qty: 1, unit: 'cup' },
      { foodId: 'turnip', qty: 1, unit: 'cup' },
      { foodId: 'cassava', qty: 1, unit: 'cup' },
      { foodId: 'olive-oil', qty: 3, unit: 'tbsp' },
      { foodId: 'parsley', qty: 4, unit: 'tbsp' },
      { foodId: 'lemon', qty: 1, unit: 'fruit' },
      { foodId: 'sea-salt', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      'Cut all roots to a similar size and toss with 2 tbsp oil and salt.',
      'Roast at 425F for 30-35 minutes, turning once.',
      'Blend the remaining oil with parsley and lemon juice to make a bright herb oil.',
      'Spoon the herb oil over the hot vegetables just before serving.',
    ],
    storage: 'Refrigerate up to 5 days; re-crisp in a hot oven or air fryer.',
    substitutions: ['Any low-FODMAP root works — swap freely by season.'],
    batchNotes: 'This is the anchor batch-prep side for the week; make a full sheet pan.',
    tags: ['aip-friendly', 'vegan', 'batch-prep', 'low-fodmap'],
  },
  {
    id: 'zucchini-noodles-basil-oil',
    name: 'Zucchini noodles with basil oil and roasted squash',
    cuisine: ['italian'],
    mealTypes: ['lunch', 'dinner'],
    servings: 2,
    prepMin: 15,
    cookMin: 15,
    equipment: ['stovetop', 'blender'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'zucchini', qty: 4, unit: 'cups', note: 'spiralized' },
      { foodId: 'yellow-squash', qty: 2, unit: 'cups' },
      { foodId: 'basil', qty: 6, unit: 'tbsp' },
      { foodId: 'olive-oil', qty: 3, unit: 'tbsp' },
      { foodId: 'lemon', qty: 1, unit: 'fruit' },
      { foodId: 'sea-salt', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      'Salt the zucchini noodles for 10 minutes, then pat dry — this prevents a watery sauce.',
      'Blend basil, olive oil, lemon juice, and salt into a loose herb oil.',
      'Sear the yellow squash 6-8 minutes until browned at the edges.',
      'Toss the noodles in the hot pan for 60-90 seconds only, then fold in the basil oil.',
    ],
    storage: 'Eat fresh; the basil oil keeps 4 days refrigerated.',
    substitutions: ['Spaghetti squash for the noodles if you want it warmer and softer.'],
    batchNotes: 'Make the basil oil in a double batch — it doubles as a dressing.',
    tags: ['aip-friendly', 'vegan', 'quick', 'low-fodmap'],
  },
  {
    id: 'ginger-squash-soup',
    name: 'Ginger butternut soup with coconut',
    cuisine: ['thai'],
    mealTypes: ['lunch', 'dinner'],
    servings: 4,
    prepMin: 15,
    cookMin: 30,
    equipment: ['stovetop', 'blender'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'butternut-squash', qty: 4, unit: 'cups' },
      { foodId: 'carrot', qty: 1, unit: 'cup' },
      { foodId: 'ginger', qty: 1, unit: 'tbsp' },
      { foodId: 'coconut-milk-canned', qty: 1, unit: 'cup' },
      { foodId: 'coconut-oil', qty: 1, unit: 'tbsp' },
      { foodId: 'turmeric', qty: 1, unit: 'tsp' },
      { foodId: 'sea-salt', qty: 1, unit: 'tsp' },
      { foodId: 'water', qty: 3, unit: 'cups' },
    ],
    instructions: [
      'Sweat the ginger in coconut oil for 1 minute.',
      'Add squash, carrot, turmeric, and water; simmer 25 minutes until fork-tender.',
      'Blend until completely smooth, then stir in the coconut milk off the heat.',
      'Season with salt; thin with warm water if it tightens as it cools.',
    ],
    storage: 'Refrigerate 5 days or freeze 3 months in single portions.',
    substitutions: ['Acorn or kabocha squash for butternut.'],
    batchNotes: 'Freezes exceptionally well — the best return on a 30-minute investment.',
    tags: ['aip-friendly', 'vegan', 'freezer', 'batch-prep'],
  },
  {
    id: 'cassava-veggie-wraps',
    name: 'Cassava wraps with herbed vegetables',
    cuisine: ['mexican'],
    mealTypes: ['lunch'],
    servings: 2,
    prepMin: 15,
    cookMin: 10,
    equipment: ['stovetop'],
    skill: 'beginner',
    budgetTier: 'moderate',
    ingredients: [
      { foodId: 'cassava-tortilla', qty: 4, unit: 'tortillas' },
      { foodId: 'zucchini', qty: 2, unit: 'cups' },
      { foodId: 'carrot', qty: 1, unit: 'cup', note: 'shredded' },
      { foodId: 'romaine-lettuce', qty: 2, unit: 'cups' },
      { foodId: 'avocado', qty: 1, unit: 'fruit' },
      { foodId: 'cilantro', qty: 4, unit: 'tbsp' },
      { foodId: 'lime', qty: 1, unit: 'fruit' },
      { foodId: 'olive-oil', qty: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Sauté the zucchini in olive oil until just tender, 5-6 minutes.',
      'Warm the tortillas 30 seconds per side in the dry pan.',
      'Mash the avocado with lime juice and spread it as the base layer.',
      'Fill with vegetables, lettuce, and cilantro; fold and press seam-side down for 30 seconds.',
    ],
    storage: 'Assemble to order; keep components refrigerated up to 4 days.',
    substitutions: ['Large collard leaves for a grain-free, tortilla-free wrap.'],
    batchNotes: 'Prep filling Sunday; wraps take 4 minutes on a weekday.',
    tags: ['aip-friendly', 'vegan', 'portable'],
  },
  {
    id: 'green-coconut-smoothie',
    name: 'Green coconut smoothie',
    cuisine: ['american'],
    mealTypes: ['breakfast', 'snack'],
    servings: 1,
    prepMin: 5,
    cookMin: 0,
    equipment: ['blender'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'frozen-spinach', qty: 1, unit: 'cup' },
      { foodId: 'banana-firm', qty: 1, unit: 'medium' },
      { foodId: 'coconut-milk-beverage', qty: 1, unit: 'cup' },
      { foodId: 'chia-seeds', qty: 1, unit: 'tbsp' },
      { foodId: 'ginger', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      'Blend the liquid and greens first until fully smooth.',
      'Add the banana, ginger, and chia; blend 30 more seconds.',
      'Let it sit 3 minutes so the chia thickens slightly before drinking.',
    ],
    storage: 'Drink within 24 hours; shake before drinking.',
    substitutions: ['Skip chia and add 1/4 avocado for a seed-free version.'],
    batchNotes: 'Freeze pre-portioned smoothie bags with the solids.',
    tags: ['vegan', 'quick', 'no-cook'],
  },
  {
    id: 'turkey-vegetable-skillet',
    name: 'Ground turkey and vegetable skillet',
    cuisine: ['american'],
    mealTypes: ['dinner', 'lunch'],
    servings: 3,
    prepMin: 10,
    cookMin: 20,
    equipment: ['stovetop'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'ground-turkey', qty: 16, unit: 'oz' },
      { foodId: 'zucchini', qty: 2, unit: 'cups' },
      { foodId: 'carrot', qty: 1, unit: 'cup' },
      { foodId: 'kale', qty: 3, unit: 'cups' },
      { foodId: 'olive-oil', qty: 1, unit: 'tbsp' },
      { foodId: 'oregano', qty: 2, unit: 'tsp' },
      { foodId: 'sea-salt', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      'Brown the turkey in oil over medium-high heat without stirring for the first 3 minutes.',
      'Add carrot and zucchini; cook 6-8 minutes.',
      'Fold in the kale and oregano and cook until just wilted.',
      'Season and finish with a splash of water to pull the pan sauce together.',
    ],
    storage: 'Refrigerate 4 days; freezes 2 months.',
    substitutions: ['Ground beef, bison, or crumbled tempeh all work.'],
    batchNotes: 'The best weeknight batch base — portion into 4 containers.',
    tags: ['high-protein', 'batch-prep', 'one-pan', 'low-fodmap'],
  },
  {
    id: 'lentil-quinoa-power-bowl',
    name: 'Lentil quinoa power bowl',
    cuisine: ['mediterranean'],
    mealTypes: ['lunch', 'dinner'],
    servings: 2,
    prepMin: 15,
    cookMin: 20,
    equipment: ['stovetop'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'lentils-canned-rinsed', qty: 1, unit: 'cup' },
      { foodId: 'quinoa', qty: 1, unit: 'cup cooked' },
      { foodId: 'cucumber', qty: 1, unit: 'cup' },
      { foodId: 'cherry-tomatoes', qty: 1, unit: 'cup' },
      { foodId: 'parsley', qty: 4, unit: 'tbsp' },
      { foodId: 'olive-oil', qty: 2, unit: 'tbsp' },
      { foodId: 'lemon', qty: 1, unit: 'fruit' },
      { foodId: 'tahini', qty: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Cook the quinoa in a 1:1.75 ratio of grain to water; rest 10 minutes off the heat.',
      'Rinse the lentils thoroughly under cold water.',
      'Whisk tahini, lemon juice, oil, and 2 tbsp water into a pourable dressing.',
      'Build the bowl warm, dress, and finish with parsley.',
    ],
    storage: 'Keep dressing separate; components hold 4 days.',
    substitutions: ['Chickpeas for lentils; rice for quinoa.'],
    batchNotes: 'Cook a double batch of quinoa for the week.',
    tags: ['vegan', 'plant-protein', 'batch-prep'],
  },
  {
    id: 'tofu-stirfry-coconut-aminos',
    name: 'Crispy tofu stir-fry with coconut aminos',
    cuisine: ['asian'],
    mealTypes: ['dinner', 'lunch'],
    servings: 2,
    prepMin: 15,
    cookMin: 15,
    equipment: ['stovetop'],
    skill: 'comfortable',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'tofu-firm', qty: 12, unit: 'oz', note: 'pressed 20 minutes' },
      { foodId: 'bok-choy', qty: 3, unit: 'cups' },
      { foodId: 'carrot', qty: 1, unit: 'cup' },
      { foodId: 'scallion-greens', qty: 1, unit: 'cup' },
      { foodId: 'coconut-aminos', qty: 3, unit: 'tbsp' },
      { foodId: 'sesame-oil', qty: 1, unit: 'tbsp' },
      { foodId: 'ginger', qty: 2, unit: 'tsp' },
      { foodId: 'white-rice', qty: 2, unit: 'cups cooked' },
    ],
    instructions: [
      'Press the tofu, cube it, and sear undisturbed until each face is golden.',
      'Remove the tofu; stir-fry carrot 2 minutes, then bok choy 2 minutes.',
      'Return the tofu, add ginger and coconut aminos, and toss 60 seconds.',
      'Finish with scallion greens and sesame oil off the heat; serve over rice.',
    ],
    storage: 'Refrigerate 3 days; the tofu softens, so re-crisp in a hot pan.',
    substitutions: ['Tamari for coconut aminos if soy is fine and you want it saltier.', 'Chicken for tofu.'],
    batchNotes: 'Press two blocks of tofu at once and sear both.',
    tags: ['vegan', 'plant-protein', 'quick'],
  },
  {
    id: 'greek-yogurt-berry-bowl',
    name: 'Greek yogurt berry bowl',
    cuisine: ['mediterranean'],
    mealTypes: ['breakfast', 'snack'],
    servings: 1,
    prepMin: 5,
    cookMin: 0,
    equipment: [],
    skill: 'beginner',
    budgetTier: 'moderate',
    ingredients: [
      { foodId: 'greek-yogurt-plain', qty: 6, unit: 'oz' },
      { foodId: 'blueberries', qty: 0.75, unit: 'cup' },
      { foodId: 'walnuts', qty: 1, unit: 'oz' },
      { foodId: 'chia-seeds', qty: 1, unit: 'tbsp' },
      { foodId: 'cinnamon', qty: 0.5, unit: 'tsp' },
    ],
    instructions: [
      'Spoon the yogurt into a wide bowl so the toppings sit on top rather than sinking.',
      'Add berries, walnuts, chia, and cinnamon.',
      'Let it stand 5 minutes if you prefer a thicker, pudding-like texture.',
    ],
    storage: 'Assemble fresh; jar-layer up to 2 days ahead without nuts.',
    substitutions: ['Coconut yogurt for a dairy-free version.', 'Pumpkin seeds for a nut-free version.'],
    batchNotes: 'Portion yogurt into jars Sunday night.',
    tags: ['high-protein', 'no-cook', 'quick'],
  },
  {
    id: 'overnight-oats-protein',
    name: 'Protein overnight oats',
    cuisine: ['american'],
    mealTypes: ['breakfast'],
    servings: 2,
    prepMin: 8,
    cookMin: 0,
    equipment: [],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'rolled-oats', qty: 1, unit: 'cup' },
      { foodId: 'almond-milk-unsweetened', qty: 1.5, unit: 'cups' },
      { foodId: 'protein-powder-whey', qty: 1, unit: 'scoop' },
      { foodId: 'chia-seeds', qty: 2, unit: 'tbsp' },
      { foodId: 'strawberries', qty: 1, unit: 'cup' },
      { foodId: 'cinnamon', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      'Whisk the protein powder into the milk first so it does not clump.',
      'Stir in oats, chia, and cinnamon; divide into two jars.',
      'Refrigerate at least 6 hours.',
      'Top with berries in the morning.',
    ],
    storage: 'Refrigerate up to 4 days.',
    substitutions: ['Pea protein for whey.', 'Certified gluten-free oats if needed.'],
    batchNotes: 'Make four jars at once — the whole week of breakfasts in 10 minutes.',
    tags: ['high-protein', 'batch-prep', 'no-cook'],
  },
  {
    id: 'veggie-egg-scramble',
    name: 'Soft scramble with greens and herbs',
    cuisine: ['french'],
    mealTypes: ['breakfast', 'lunch'],
    servings: 1,
    prepMin: 5,
    cookMin: 8,
    equipment: ['stovetop'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'chicken-eggs', qty: 3, unit: 'large' },
      { foodId: 'spinach', qty: 1, unit: 'cup' },
      { foodId: 'olive-oil', qty: 1, unit: 'tbsp' },
      { foodId: 'scallion-greens', qty: 0.25, unit: 'cup' },
      { foodId: 'sea-salt', qty: 0.5, unit: 'tsp' },
    ],
    instructions: [
      'Wilt the spinach in oil for 60 seconds and push it to one side.',
      'Add the beaten eggs over low heat and stir constantly with a spatula.',
      'Pull the pan off the heat while the eggs still look slightly underdone.',
      'Fold in the greens, salt, and scallion greens.',
    ],
    storage: 'Eat immediately — eggs do not reheat well.',
    substitutions: ['Crumbled tofu for a vegan version (add nutritional yeast).'],
    batchNotes: 'Not a batch dish; keep pre-washed greens ready instead.',
    tags: ['high-protein', 'quick', 'low-fodmap'],
  },
  {
    id: 'beef-and-broccoli-bowl',
    name: 'Seared beef and broccoli rice bowl',
    cuisine: ['asian'],
    mealTypes: ['dinner'],
    servings: 2,
    prepMin: 12,
    cookMin: 15,
    equipment: ['stovetop'],
    skill: 'comfortable',
    budgetTier: 'moderate',
    ingredients: [
      { foodId: 'beef-sirloin', qty: 12, unit: 'oz', note: 'sliced thin across the grain' },
      { foodId: 'broccoli', qty: 3, unit: 'cups' },
      { foodId: 'tamari', qty: 2, unit: 'tbsp' },
      { foodId: 'ginger', qty: 2, unit: 'tsp' },
      { foodId: 'sesame-oil', qty: 1, unit: 'tbsp' },
      { foodId: 'jasmine-rice', qty: 2, unit: 'cups cooked' },
      { foodId: 'sesame-seeds', qty: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Get the pan very hot and sear the beef in a single layer for 90 seconds per side.',
      'Remove the beef; steam the broccoli in 1/4 cup water, covered, for 4 minutes.',
      'Return the beef with tamari and ginger; toss 60 seconds.',
      'Serve over rice with sesame oil and seeds.',
    ],
    storage: 'Refrigerate 3 days. Reheat gently so the beef does not toughen.',
    substitutions: ['Coconut aminos for tamari (soy-free).', 'Green beans for broccoli (lower FODMAP).'],
    batchNotes: 'Cook the rice ahead; the stir-fry is a 15-minute job.',
    tags: ['high-protein', 'quick'],
  },
  {
    id: 'shrimp-zucchini-scampi',
    name: 'Shrimp scampi with zucchini ribbons',
    cuisine: ['italian'],
    mealTypes: ['dinner'],
    servings: 2,
    prepMin: 10,
    cookMin: 12,
    equipment: ['stovetop'],
    skill: 'comfortable',
    budgetTier: 'flexible',
    ingredients: [
      { foodId: 'shrimp', qty: 12, unit: 'oz' },
      { foodId: 'zucchini', qty: 4, unit: 'cups', note: 'ribboned' },
      { foodId: 'olive-oil', qty: 2, unit: 'tbsp' },
      { foodId: 'lemon', qty: 1, unit: 'fruit' },
      { foodId: 'parsley', qty: 4, unit: 'tbsp' },
      { foodId: 'black-pepper', qty: 0.5, unit: 'tsp' },
      { foodId: 'sea-salt', qty: 0.5, unit: 'tsp' },
    ],
    instructions: [
      'Pat the shrimp dry and sear 90 seconds per side; remove.',
      'Add the zucchini ribbons and cook 2 minutes only.',
      'Return the shrimp with lemon juice, oil, salt, and pepper.',
      'Finish with parsley off the heat.',
    ],
    storage: 'Best fresh; 2 days refrigerated.',
    substitutions: ['Scallops or cod for shrimp.', 'Garlic-infused oil if you tolerate it and want the classic flavor.'],
    batchNotes: 'Ribbon the zucchini ahead and store on a paper towel.',
    tags: ['high-protein', 'quick', 'low-fodmap'],
  },
  {
    id: 'slow-cooker-pork-cabbage',
    name: 'Slow-cooker pork shoulder with cabbage',
    cuisine: ['american'],
    mealTypes: ['dinner'],
    servings: 6,
    prepMin: 10,
    cookMin: 300,
    equipment: ['slow cooker'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'pork-shoulder', qty: 32, unit: 'oz' },
      { foodId: 'cabbage', qty: 4, unit: 'cups' },
      { foodId: 'carrot', qty: 2, unit: 'cups' },
      { foodId: 'apple-cider-vinegar', qty: 2, unit: 'tbsp' },
      { foodId: 'bone-broth-chicken', qty: 1, unit: 'cup' },
      { foodId: 'thyme', qty: 2, unit: 'tsp' },
      { foodId: 'sea-salt', qty: 1.5, unit: 'tsp' },
    ],
    instructions: [
      'Salt the pork and set it in the cooker with broth, vinegar, and thyme.',
      'Cook on low 5-6 hours until it shreds with a fork.',
      'Add cabbage and carrot for the final 45 minutes.',
      'Shred the pork into the juices before serving.',
    ],
    storage: 'Refrigerate 4 days, freeze 3 months in the cooking liquid.',
    substitutions: ['Chuck roast for pork shoulder.'],
    batchNotes: 'This is the single best cost-per-serving batch cook in the book.',
    tags: ['batch-prep', 'high-protein', 'budget', 'low-fodmap'],
  },
  {
    id: 'chickpea-vegetable-curry',
    name: 'Chickpea and vegetable coconut curry',
    cuisine: ['indian'],
    mealTypes: ['dinner', 'lunch'],
    servings: 4,
    prepMin: 15,
    cookMin: 25,
    equipment: ['stovetop'],
    skill: 'comfortable',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'chickpeas', qty: 2, unit: 'cups' },
      { foodId: 'coconut-milk-canned', qty: 1, unit: 'cup' },
      { foodId: 'spinach', qty: 3, unit: 'cups' },
      { foodId: 'carrot', qty: 1, unit: 'cup' },
      { foodId: 'turmeric', qty: 1, unit: 'tsp' },
      { foodId: 'cumin', qty: 2, unit: 'tsp' },
      { foodId: 'ginger', qty: 1, unit: 'tbsp' },
      { foodId: 'brown-rice', qty: 3, unit: 'cups cooked' },
    ],
    instructions: [
      'Bloom cumin and turmeric in oil for 45 seconds.',
      'Add ginger and carrot; cook 5 minutes.',
      'Add chickpeas and coconut milk; simmer 15 minutes.',
      'Wilt in the spinach at the end and serve over rice.',
    ],
    storage: 'Refrigerate 4 days, freeze 2 months.',
    substitutions: ['Lentils for chickpeas.', 'Cauliflower rice for a lower-carb base.'],
    batchNotes: 'Doubles in one pot; freeze half immediately.',
    tags: ['vegan', 'plant-protein', 'batch-prep'],
  },
  {
    id: 'salmon-rice-bowl-cucumber',
    name: 'Canned salmon rice bowl with cucumber',
    cuisine: ['asian'],
    mealTypes: ['lunch'],
    servings: 1,
    prepMin: 8,
    cookMin: 0,
    equipment: [],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'canned-salmon', qty: 1, unit: 'can' },
      { foodId: 'white-rice', qty: 1, unit: 'cup cooked' },
      { foodId: 'cucumber', qty: 1, unit: 'cup' },
      { foodId: 'seaweed-nori', qty: 2, unit: 'sheets' },
      { foodId: 'coconut-aminos', qty: 1, unit: 'tbsp' },
      { foodId: 'sesame-seeds', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      'Warm the rice and spread it in a shallow bowl.',
      'Flake the salmon over the top and add cucumber.',
      'Drizzle with coconut aminos and scatter sesame and torn nori.',
    ],
    storage: 'Assemble same day; keep rice and salmon separate until serving.',
    substitutions: ['Canned tuna or sardines.', 'Quinoa for rice.'],
    batchNotes: 'The five-minute desk lunch — keep cans and cooked rice on hand.',
    tags: ['high-protein', 'no-cook', 'budget', 'omega3'],
  },
  {
    id: 'tempeh-kale-hash',
    name: 'Tempeh and kale breakfast hash',
    cuisine: ['american'],
    mealTypes: ['breakfast', 'lunch'],
    servings: 2,
    prepMin: 10,
    cookMin: 18,
    equipment: ['stovetop'],
    skill: 'comfortable',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'tempeh', qty: 8, unit: 'oz', note: 'crumbled' },
      { foodId: 'sweet-potato', qty: 2, unit: 'cups', note: 'small dice' },
      { foodId: 'kale', qty: 3, unit: 'cups' },
      { foodId: 'olive-oil', qty: 2, unit: 'tbsp' },
      { foodId: 'turmeric', qty: 1, unit: 'tsp' },
      { foodId: 'nutritional-yeast', qty: 2, unit: 'tbsp' },
      { foodId: 'sea-salt', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      'Cook the sweet potato covered for 8 minutes, then uncovered to brown.',
      'Add the tempeh and turmeric; cook 5 minutes without stirring much.',
      'Fold in the kale until wilted.',
      'Finish with nutritional yeast and salt.',
    ],
    storage: 'Refrigerate 4 days; reheats well in a skillet.',
    substitutions: ['Ground turkey for tempeh.', 'Cassava for sweet potato.'],
    batchNotes: 'Dice the sweet potato for the whole week at once.',
    tags: ['vegan', 'plant-protein', 'batch-prep'],
  },
  {
    id: 'cod-with-herb-butter-greens',
    name: 'Pan-roasted cod with herb oil and greens',
    cuisine: ['french'],
    mealTypes: ['dinner'],
    servings: 2,
    prepMin: 10,
    cookMin: 14,
    equipment: ['stovetop', 'oven'],
    skill: 'comfortable',
    budgetTier: 'moderate',
    ingredients: [
      { foodId: 'cod', qty: 12, unit: 'oz' },
      { foodId: 'swiss-chard', qty: 4, unit: 'cups' },
      { foodId: 'olive-oil', qty: 2, unit: 'tbsp' },
      { foodId: 'dill', qty: 3, unit: 'tbsp' },
      { foodId: 'lemon', qty: 1, unit: 'fruit' },
      { foodId: 'sea-salt', qty: 0.75, unit: 'tsp' },
    ],
    instructions: [
      'Pat the cod very dry and sear 3 minutes in a hot oven-safe pan.',
      'Flip and transfer to a 400F oven for 6-8 minutes.',
      'Wilt the chard in the same pan with oil and a splash of water.',
      'Dress with lemon and dill.',
    ],
    storage: 'Best fresh; 2 days refrigerated.',
    substitutions: ['Halibut or tilapia.', 'Spinach for chard.'],
    batchNotes: 'Cook chard in bulk; cook fish to order.',
    tags: ['high-protein', 'quick', 'low-fodmap'],
  },
  {
    id: 'quinoa-stuffed-squash',
    name: 'Quinoa-stuffed acorn squash',
    cuisine: ['american'],
    mealTypes: ['dinner'],
    servings: 2,
    prepMin: 15,
    cookMin: 45,
    equipment: ['oven', 'stovetop'],
    skill: 'comfortable',
    budgetTier: 'moderate',
    ingredients: [
      { foodId: 'acorn-squash', qty: 2, unit: 'halves' },
      { foodId: 'quinoa', qty: 1.5, unit: 'cups cooked' },
      { foodId: 'pumpkin-seeds', qty: 1, unit: 'oz' },
      { foodId: 'kale', qty: 2, unit: 'cups' },
      { foodId: 'olive-oil', qty: 2, unit: 'tbsp' },
      { foodId: 'cinnamon', qty: 0.5, unit: 'tsp' },
      { foodId: 'sea-salt', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      'Roast the squash halves cut-side down at 400F for 30 minutes.',
      'Sauté the kale and fold it into the cooked quinoa with cinnamon and salt.',
      'Fill the squash, top with pumpkin seeds, and roast 12 more minutes.',
    ],
    storage: 'Refrigerate 4 days; reheat covered at 350F.',
    substitutions: ['Millet or rice for quinoa.', 'Sunflower seeds for pumpkin seeds.'],
    batchNotes: 'Roast four halves and fill two at a time.',
    tags: ['vegan', 'plant-protein'],
  },
  {
    id: 'chicken-cabbage-crunch-salad',
    name: 'Chicken cabbage crunch salad',
    cuisine: ['asian'],
    mealTypes: ['lunch'],
    servings: 2,
    prepMin: 15,
    cookMin: 0,
    equipment: [],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'rotisserie-chicken', qty: 8, unit: 'oz', note: 'shredded' },
      { foodId: 'cabbage', qty: 3, unit: 'cups', note: 'shredded' },
      { foodId: 'carrot', qty: 1, unit: 'cup' },
      { foodId: 'cilantro', qty: 4, unit: 'tbsp' },
      { foodId: 'tahini', qty: 2, unit: 'tbsp' },
      { foodId: 'lime', qty: 1, unit: 'fruit' },
      { foodId: 'sesame-oil', qty: 1, unit: 'tsp' },
    ],
    instructions: [
      'Whisk tahini, lime juice, sesame oil, and 2 tbsp water into a dressing.',
      'Toss the cabbage and carrot with the dressing and let it sit 10 minutes to soften.',
      'Fold in the chicken and cilantro.',
    ],
    storage: 'Holds 2 days dressed — it gets better, not worse.',
    substitutions: ['Chickpeas for chicken.', 'Sunflower butter for tahini.'],
    batchNotes: 'Uses a store rotisserie chicken deliberately: zero cook time.',
    tags: ['high-protein', 'no-cook', 'quick', 'budget'],
  },
  {
    id: 'sardine-toast-arugula',
    name: 'Sardine toast with arugula and lemon',
    cuisine: ['mediterranean'],
    mealTypes: ['lunch', 'snack'],
    servings: 1,
    prepMin: 6,
    cookMin: 3,
    equipment: ['stovetop'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'sardines', qty: 1, unit: 'can' },
      { foodId: 'sourdough-bread', qty: 2, unit: 'slices' },
      { foodId: 'arugula', qty: 2, unit: 'cups' },
      { foodId: 'olive-oil', qty: 1, unit: 'tbsp' },
      { foodId: 'lemon', qty: 0.5, unit: 'fruit' },
      { foodId: 'black-pepper', qty: 0.25, unit: 'tsp' },
    ],
    instructions: [
      'Toast the bread until firm enough to hold the topping.',
      'Layer arugula, then sardines, then oil, lemon, and pepper.',
    ],
    storage: 'Eat immediately.',
    substitutions: ['Gluten-free bread or rice cakes.', 'Canned salmon for sardines.'],
    batchNotes: 'Pantry meal — keep sardines stocked for low-effort days.',
    tags: ['omega3', 'quick', 'budget'],
  },
  {
    id: 'air-fryer-chicken-thighs',
    name: 'Air fryer chicken thighs with herb rub',
    cuisine: ['american'],
    mealTypes: ['dinner'],
    servings: 2,
    prepMin: 8,
    cookMin: 22,
    equipment: ['air fryer'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'chicken-thigh', qty: 16, unit: 'oz' },
      { foodId: 'olive-oil', qty: 1, unit: 'tbsp' },
      { foodId: 'oregano', qty: 2, unit: 'tsp' },
      { foodId: 'thyme', qty: 1, unit: 'tsp' },
      { foodId: 'sea-salt', qty: 1, unit: 'tsp' },
      { foodId: 'green-beans', qty: 3, unit: 'cups' },
    ],
    instructions: [
      'Rub the thighs with oil, herbs, and salt.',
      'Air fry at 380F for 18-22 minutes, skin-side up, no flipping.',
      'Add the green beans to the basket for the final 8 minutes.',
    ],
    storage: 'Refrigerate 4 days; the air fryer reheats them perfectly at 350F for 4 minutes.',
    substitutions: ['Oven at 425F for 30 minutes.'],
    batchNotes: 'Cook two batches back to back; the second needs no preheat.',
    tags: ['high-protein', 'quick', 'low-fodmap'],
  },
  {
    id: 'blueberry-chia-pudding',
    name: 'Blueberry chia pudding',
    cuisine: ['american'],
    mealTypes: ['breakfast', 'snack', 'dessert'],
    servings: 2,
    prepMin: 6,
    cookMin: 0,
    equipment: [],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'chia-seeds', qty: 4, unit: 'tbsp' },
      { foodId: 'coconut-milk-beverage', qty: 1.5, unit: 'cups' },
      { foodId: 'blueberries', qty: 1, unit: 'cup' },
      { foodId: 'maple-syrup', qty: 1, unit: 'tsp' },
      { foodId: 'cinnamon', qty: 0.5, unit: 'tsp' },
    ],
    instructions: [
      'Whisk chia into the milk and wait 5 minutes, then whisk again to break up clumps.',
      'Refrigerate at least 3 hours.',
      'Top with blueberries, a thread of maple syrup, and cinnamon.',
    ],
    storage: 'Refrigerate 5 days.',
    substitutions: ['Any unsweetened milk.', 'Skip the syrup entirely for a blood-sugar-supportive version.'],
    batchNotes: 'One jar per day of the week in 10 minutes.',
    tags: ['vegan', 'no-cook', 'batch-prep'],
  },
  {
    id: 'roasted-cauliflower-tahini-plate',
    name: 'Roasted cauliflower with tahini and herbs',
    cuisine: ['middle-eastern'],
    mealTypes: ['dinner', 'lunch'],
    servings: 2,
    prepMin: 10,
    cookMin: 30,
    equipment: ['oven'],
    skill: 'beginner',
    budgetTier: 'tight',
    ingredients: [
      { foodId: 'cauliflower', qty: 4, unit: 'cups' },
      { foodId: 'tahini', qty: 3, unit: 'tbsp' },
      { foodId: 'lemon', qty: 1, unit: 'fruit' },
      { foodId: 'parsley', qty: 4, unit: 'tbsp' },
      { foodId: 'olive-oil', qty: 2, unit: 'tbsp' },
      { foodId: 'cumin', qty: 1, unit: 'tsp' },
      { foodId: 'chickpeas', qty: 1, unit: 'cup' },
    ],
    instructions: [
      'Roast cauliflower and chickpeas at 425F with oil and cumin for 28-30 minutes.',
      'Thin the tahini with lemon juice and water until pourable.',
      'Plate the vegetables, pour over the tahini, and finish with parsley.',
    ],
    storage: 'Refrigerate 4 days; sauce separately.',
    substitutions: ['Broccoli for cauliflower (lower FODMAP).', 'Sunflower butter for tahini.'],
    batchNotes: 'Roast a full sheet pan and use it across three lunches.',
    tags: ['vegan', 'plant-protein', 'batch-prep'],
  },
];

// Defensive integrity check: every ingredient must resolve to a seed food.
for (const r of RECIPES) {
  for (const ing of r.ingredients) {
    if (!getFood(ing.foodId)) console.warn('[recipes] unknown foodId', r.id, ing.foodId);
  }
}

const byId = new Map(RECIPES.map((r) => [r.id, r]));
export const getRecipe = (id) => byId.get(id) || null;
export const RECIPE_COUNT = RECIPES.length;

/** Estimated nutrition per serving, derived from the seed food data. */
export function estimateNutrition(recipe, servings = recipe.servings) {
  let cal = 0;
  let protein = 0;
  for (const ing of recipe.ingredients) {
    const f = getFood(ing.foodId);
    if (!f) continue;
    const factor = Math.max(0.25, Number(ing.qty) || 1) * unitFactor(ing.unit, f);
    cal += f.calories * factor;
    protein += f.protein * factor;
  }
  const per = Math.max(1, servings);
  return {
    calories: Math.round(cal / per / 5) * 5,
    protein: Math.round(protein / per),
    estimated: true,
  };
}

function unitFactor(unit, food) {
  const u = String(unit || '').toLowerCase();
  const serving = String(food.serving || '').toLowerCase();
  if (!u) return 1;
  if (u.includes('oz') && serving.includes('oz')) {
    const base = parseFloat(serving) || 4;
    return 1 / base;
  }
  if (u.includes('cup') && serving.includes('cup')) return 1;
  if (u.includes('tbsp') && serving.includes('tbsp')) return 1 / (parseFloat(serving) || 1);
  if (u.includes('tsp') && serving.includes('tsp')) return 1;
  if (u.includes('tbsp') && serving.includes('cup')) return 1 / 16;
  return 0.5;
}

/**
 * Ingredient-by-ingredient compliance check.
 * rulingFor(foodId) must return { status } where status is one of
 * 'Avoid' | 'Eat in moderation' | 'Eat freely' | 'Occasional'.
 */
export function checkRecipeCompliance(recipe, rulingFor, opts = {}) {
  const blocked = [];
  const caution = [];
  for (const ing of recipe.ingredients) {
    const food = getFood(ing.foodId);
    if (!food) continue;
    const ruling = rulingFor(food.id);
    if (!ruling) continue;
    if (ruling.status === 'Avoid') blocked.push({ food, ruling });
    else if (ruling.status === 'Eat in moderation' || ruling.status === 'Occasional') caution.push({ food, ruling });
  }
  const equipmentOk = !opts.equipment || recipe.equipment.every((e) => opts.equipment.includes(e));
  const budgetOk =
    !opts.budget ||
    opts.budget === 'flexible' ||
    (opts.budget === 'moderate' ? recipe.budgetTier !== 'flexible' : recipe.budgetTier === 'tight');
  const timeOk = !opts.maxMinutes || recipe.prepMin + Math.min(recipe.cookMin, 45) <= opts.maxMinutes || recipe.tags.includes('batch-prep');
  return {
    compliant: blocked.length === 0 && equipmentOk && budgetOk && timeOk,
    blocked,
    caution,
    equipmentOk,
    budgetOk,
    timeOk,
  };
}
